---
- hosts: all
  tasks:
  - name: Set wsrep_on=ON
    ini_file:
      path: /etc/my.cnf.d/server.cnf
      section: galera
      option: wsrep_on
      value: "ON"
      no_extra_spaces: yes
  - name: Set wsrep_provider=/usr/lib64/galera-4/libgalera_smm.so
    ini_file:
      path: /etc/my.cnf.d/server.cnf
      section: galera
      option: wsrep_provider
      value: "/usr/lib64/galera-4/libgalera_smm.so"
      no_extra_spaces: yes
  - name: Set server_id=40
    ini_file:
      path: /etc/my.cnf.d/server.cnf
      section: galera
      option: server_id
      value: "40"
      no_extra_spaces: yes
  - name: Set log_slave_updates=ON
    ini_file:
      path: /etc/my.cnf.d/server.cnf
      section: galera
      option: log_slave_updates
      value: "ON"
      no_extra_spaces: yes
  - name: Set log_bin
    ini_file:
      path: /etc/my.cnf.d/server.cnf
      section: galera
      option: log_bin
      value: "binlog"
      no_extra_spaces: yes
  - name: Set wsrep_gtid_domain_id=40
    ini_file:
      path: /etc/my.cnf.d/server.cnf
      section: galera
      option: wsrep_gtid_domain_id
      value: "40"
      no_extra_spaces: yes
  - name: Set wsrep_gtid_mode=ON
    ini_file:
      path: /etc/my.cnf.d/server.cnf
      section: galera
      option: wsrep_gtid_mode
      value: "ON"
      no_extra_spaces: yes
  - name: Set binlog_format=row
    ini_file:
      path: /etc/my.cnf.d/server.cnf
      section: galera
      option: binlog_format
      value: "row"
      no_extra_spaces: yes
  - name: Set wsrep_provider_options
    ini_file:
      path: /etc/my.cnf.d/server.cnf
      section: galera
      option: wsrep_provider_options
      value: "\"gmcast.mcast_addr=239.192.0.22\""
      no_extra_spaces: yes
  - name: Set wsrep_cluster_address
    ini_file:
      path: /etc/my.cnf.d/server.cnf
      section: galera
      option: wsrep_cluster_address
      value: "gcomm://239.192.0.21"
      no_extra_spaces: yes
  - name: Set default_storage_engine=InnoDB
    ini_file:
      path: /etc/my.cnf.d/server.cnf
      section: galera
      option: default_storage_engine
      value: "InnoDB"
      no_extra_spaces: yes
  - name: Set innodb_autoinc_lock_mode=2
    ini_file:
      path: /etc/my.cnf.d/server.cnf
      section: galera
      option: innodb_autoinc_lock_mode
      value: "2"
      no_extra_spaces: yes
  - name: Set innodb_flush_log_at_trx_commit=0
    ini_file:
      path: /etc/my.cnf.d/server.cnf
      section: galera
      option: innodb_flush_log_at_trx_commit
      value: "0"
      no_extra_spaces: yes
  - name: Set wsrep_sst_method=mariabackup
    ini_file:
      path: /etc/my.cnf.d/server.cnf
      section: mariadb
      option: wsrep_sst_method
      value: "mariabackup"
      no_extra_spaces: yes
  - name: Set "wsrep_sst_auth=mysql:"
    ini_file:
      path: /etc/my.cnf.d/server.cnf
      section: mariadb
      option: wsrep_sst_auth
      value: "mysql:"
      no_extra_spaces: yes
  - name: Set "innodb_compression_algorithm=lzma"
    ini_file:
      path: /etc/my.cnf.d/server.cnf
      section: mariadb
      option: innodb_compression_algorithm
      value: "lzma"
      no_extra_spaces: yes
  - name: Set "innodb_compression_default=ON"
    ini_file:
      path: /etc/my.cnf.d/server.cnf
      section: mariadb
      option: innodb_compression_default
      value: "ON"
      no_extra_spaces: yes
